/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"
int row1,row2,col1,col2;
float mat1[100][100],mat2[100][100];

output calculate_prog_1(char *host,char opr,CLIENT *clnt)
{

    output  *result_1;
    inputs  add_1_arg;
    output  *result_2;
    inputs  sub_1_arg;
    output  *result_3;
    inputs  mul_1_arg;
    output  *result_4;
    inputs  inv_1_arg;
    output  *result_5;
    inputs  trans_1_arg;
//client operation check kortese
    if(opr=='+')
    {

// add_1_arg.num1=n1;
// add_1_arg.num2=n2;

        int cnt1=0,cnt2=0;
        for(int i=0; i<row1; i++)
        {
            for(int j=0; j<col1; j++)
            {//stub e msg assign kortese
                add_1_arg.num1[cnt1]=mat1[i][j];
                cnt1++;
            }
        }
        for(int i=0; i<row2; i++)
        {
            for(int j=0; j<col2; j++)
            {
                add_1_arg.num2[cnt2]=mat2[i][j];
                cnt2++;
            }
        }

        add_1_arg.r1=row1;
        add_1_arg.c1=col1;
        add_1_arg.r2=row2;
        add_1_arg.c2=col2;
        add_1_arg.operator=opr;
//stub e messge parameters  pass
        result_1 = add_1(&add_1_arg, clnt);
        int cnt=0;
        printf("Ans:\n");
        printf("------------------------------\n");
        //result check kortese
        if(result_1->flag==0)
        {

            printf("Matrix Dimension Error\n");
        }
        else//answer print kortese
        {
            for(int i=0; i<row1; i++)
            {
                for(int j=0; j<col1; j++)

                {
                    printf("%f ",result_1->a[cnt++]);
                }
                printf("\n");

            }
            printf("------------------------------\n");
        }
        //*res=add_1(&add_1_arg,clnt);
        //res=*result_1;
        if (result_1 == (output *) NULL)
        {
            clnt_perror (clnt, "call failed");
        }
        return *result_1;
    }

    else if(opr=='-')
    {

//sub_1_arg.num1=n1;
//sub_1_arg.num2=n2;
        sub_1_arg.operator=opr;
        int cnt1=0,cnt2=0;
        for(int i=0; i<row1; i++)
        {
            for(int j=0; j<col1; j++)
            {
                sub_1_arg.num1[cnt1]=mat1[i][j];
                cnt1++;
            }
        }
        for(int i=0; i<row2; i++)
        {
            for(int j=0; j<col2; j++)
            {
                sub_1_arg.num2[cnt2]=mat2[i][j];
                cnt2++;
            }
        }
        sub_1_arg.r1=row1;
        sub_1_arg.r2=row2;
        sub_1_arg.c1=col1;
        sub_1_arg.c2=col2;

        result_2 = sub_1(&sub_1_arg, clnt);
        int cnt=0;
        printf("Ans:\n");
        printf("------------------------------\n");
        if(result_2->flag==0)
        {

            printf("Matrix Dimension Error\n");
        }
        else
        {
            for(int i=0; i<row1; i++)
            {
                for(int j=0; j<col1; j++)
                {
                    printf("%f ",result_2->a[cnt++]);
                }
                printf("\n");
                printf("------------------------------\n");
            }
        }
        if (result_2 == (output *) NULL)
        {
            clnt_perror (clnt, "call failed");
        }
        return *result_2;
    }

    else if(opr=='*')
    {

        int cnt1=0,cnt2=0;
        for(int i=0; i<row1; i++)
        {
            for(int j=0; j<col1; j++)
            {
                mul_1_arg.num1[cnt1]=mat1[i][j];
                cnt1++;
            }
        }
        for(int i=0; i<row2; i++)
        {
            for(int j=0; j<col2; j++)
            {
                mul_1_arg.num2[cnt2]=mat2[i][j];
                cnt2++;
            }
        }

// mul_1_arg.num1=n1;
// mul_1_arg.num2=n2;
        mul_1_arg.r2=row2;
        mul_1_arg.r1=row1;
        mul_1_arg.c1=col1;
        mul_1_arg.c2=col2;
        mul_1_arg.operator=opr;

        result_3 = mul_1(&mul_1_arg, clnt);
        int cnt=0;
        printf("Ans:\n");
        printf("------------------------------\n");
        if(result_3->flag==0)
        {

            printf("Matrix Dimension Error\n");
        }
        else
        {
            for(int i=0; i<row1; i++)
            {
                for(int j=0; j<col2; j++)
                {
                    printf("%f ",result_3->a[cnt++]);
                }
                printf("\n");

            }
            printf("------------------------------\n");
        }
        if (result_3 == (output *) NULL)
        {
            clnt_perror (clnt, "call failed");
        }
        return *result_3;
    }

    else if(opr=='i'||opr=='I')
    {

//div_1_arg.num1=n1;
//div_1_arg.num2=n2;
        int cnt1=0,cnt2=0;
        for(int i=0; i<row1; i++)
        {
            for(int j=0; j<col1; j++)
            {
                inv_1_arg.num1[cnt1]=mat1[i][j];
                cnt1++;
            }
        }

        inv_1_arg.r1=row1;
        inv_1_arg.c1=col1;
        inv_1_arg.operator=opr;

//if(n2 == 0){
//printf("Division by zero is not valid.\n");
//exit(0);
//}else{

        result_4 = inv_1(&inv_1_arg, clnt);
        int cnt=0;
        printf("Ans:\n");
        if(result_4->flag==0)
        {

            printf("Matrix Dimension Error\n");
        }
        else if(result_4->flag==2)
        {

            printf("Determinant zero\n");
        }
        else
        {
            printf("------------------------------\n");
            for(int i=0; i<row1; i++)
            {
                for(int j=0; j<col1; j++)
                {
                    printf("%f ",result_4->a[cnt++]);
                }
                printf("\n");



            }
            printf("------------------------------\n");
        }
        if (result_4 == (output *) NULL)
        {
            clnt_perror (clnt, "call failed");
        }
        return *result_4;
//}
    }
    else if (opr=='T'||opr=='t')
    {
        int cnt1=0,cnt2=0;
        for(int i=0; i<row1; i++)
        {
            for(int j=0; j<col1; j++)
            {
                trans_1_arg.num1[cnt1]=mat1[i][j];
                cnt1++;
            }
        }

        trans_1_arg.r1=row1;
        trans_1_arg.c1=col1;
        trans_1_arg.operator=opr;

//if(n2 == 0){
//printf("Division by zero is not valid.\n");
//exit(0);
//}else{

        result_5 = trans_1(&trans_1_arg, clnt);
        int cnt=0;
        printf("Ans:\n");
        printf("------------------------------\n");


        for(int i=0; i<col1; i++)
        {
            for(int j=0; j<row1; j++)
            {

                printf("%f ",result_5->a[cnt++]);
            }
            printf("\n");

        }
        //print("\n");
        printf("------------------------------\n");
        if (result_5 == (output *) NULL)
        {
            clnt_perror (clnt, "call failed");
        }
        return *result_5;
//}

    }
}

int main (int argc, char *argv[])
{
    char *host;

    char op;
    CLIENT *clnt;

    if (argc < 2)
    {
        printf ("usage: %s server_host\n", argv[0]);
        exit (1);
    }

    printf("Welcome to RPC!!!\n");
    printf("+ for Addition\n- for Substraction\n* for Multiplication\ni for Inversion\nT for transpose");
    printf("Enter the Operator :\n");
    scanf("%s",&op);
    printf("--------------------------------------------------------\n");
//input format

    if(op=='+'||op=='-'||op=='*')
    {
        printf("ENTER NUMBER OF ROWS AND COLUMNS OF MATRIX1\n" );
        scanf("%d %d",&row1,&col1);
        //row2=row1;
        //col2=col1;
        printf("--------------------------------------------------------\n");
        printf("ENTER MATRIX1  :\n");
        printf("--------------------------------------------------------\n");

        for(int i=0; i<row1; i++)
        {
            for(int j=0; j<col1; j++)
            {
                float temp;
                scanf("%f",&temp);
                mat1[i][j]=temp;
            }
        }
        printf("--------------------------------------------------------\n");

        printf("\nENTER NUMBER OF ROWS AND COLUMS OF MATRIX2 :\n");
        printf("--------------------------------------------------------\n");
        scanf("%d %d",&row2,&col2);
        printf("--------------------------------------------------------\n");

        printf("ENTER MATRIX2  :\n");
        printf("--------------------------------------------------------\n");

        for(int i=0; i<row2; i++)
        {
            for(int j=0; j<col2; j++)
            {
                float temp;
                scanf("%f",&temp);
                mat2[i][j]=temp;
            }
        }

    }
    else if(op=='i'||op=='I'||op=='T'||op=='t')
    {
        printf("\nENTER NUMBER OF ROWS AND COLUMS :\n");
        scanf("%d %d",&row1,&col1);
        //col1=row1;
        row2=row1;
        col2=col1;
        printf("--------------------------------------------------------\n");
        printf("ENTER MATRIX  :\n");
        printf("--------------------------------------------------------\n");

        for(int i=0; i<row1; i++)
        {
            for(int j=0; j<col1; j++)
            {
                float temp;
                scanf("%f",&temp);
                mat1[i][j]=temp;
            }
        }


    }

    host = argv[1];

    clnt = clnt_create (host, CALCULATE_PROG, CALCULATE_VER, "udp");

    if (clnt == NULL)
    {
        clnt_pcreateerror (host);
        exit (1);
    }

    calculate_prog_1 (host,op,clnt);

    clnt_destroy (clnt);

    exit (0);
}

