/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculate.h"

bool_t
xdr_inputs (XDR *xdrs, inputs *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->num1, 1000,
			sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->num2, 1000,
			sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->r1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->r2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c2))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->r1);
		IXDR_PUT_LONG(buf, objp->r2);
		IXDR_PUT_LONG(buf, objp->c1);
		IXDR_PUT_LONG(buf, objp->c2);
		}
		 if (!xdr_char (xdrs, &objp->operator))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->num1, 1000,
			sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->num2, 1000,
			sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->r1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->r2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c2))
				 return FALSE;

		} else {
		objp->r1 = IXDR_GET_LONG(buf);
		objp->r2 = IXDR_GET_LONG(buf);
		objp->c1 = IXDR_GET_LONG(buf);
		objp->c2 = IXDR_GET_LONG(buf);
		}
		 if (!xdr_char (xdrs, &objp->operator))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->num1, 1000,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->num2, 1000,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->r1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->r2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c2))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->operator))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output (XDR *xdrs, output *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->a, 1000,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->flag))
		 return FALSE;
	return TRUE;
}
